baseURL = 'https://orginux.github.io'
languageCode = 'en-us'
title = 'Denis Gorobets'  # Made more professional with full name
theme = "hugo-blog-awesome"
enableRobotsTXT = true
pygmentsStyle = "swapoff"
enableEmoji = true
defaultContentLanguage = "en-gb"  # Added for proper date formatting

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'hrdark'
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[params]
  sitename = "Denis Gorobets"
  defaultColor = "auto"  # Added theme color mode support
  description = "Data Infrastructure Engineer | Architecting Scalable Real-Time Data Systems with ClickHouse"
  mainSections = ['posts']  # Added to control main content sections
  toc = true  # Enable table of contents globally
  goToTop = true  # Enable "go to top" button
  dateFormat = "2 Jan 2006"  # Added date format
  rssFeedDescription = "summary"  # Added RSS feed configuration
  metaKeywords = ["clickhouse", "go", "devops", "linux", "duckdb", "golang", "data"]

[menu]
  [[menu.main]]
    pageRef = "/"  # Added pageRef for menu highlighting
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    pageRef = "posts"
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    pageRef = "tags"
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[params.author]
  avatar = "avatar.jpg"  # Add your avatar image
  intro = "Gorobets Denis"
  name = "Gorobets Denis"
  description = "Data Infrastructure Engineer | Architecting Scalable Real-Time Data Systems with ClickHouse"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/orginux"

[[params.socialIcons]]
name = "github"
url = "https://github.com/orginux"

[[params.socialIcons]]
name = "kaggle"
url = "https://www.kaggle.com/denisgorobets"

[[params.socialIcons]]
name = "email"
url = "mailto:orginux@pm.me"

[[params.socialIcons]]
name = "rss"
url = "index.xml"  # Added RSS feed

# Privacy settings (added)
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = false  # Keep GA enabled since you're using it
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

# Google Analytics (moved to privacy section)
customHeadHTML = '''
<script async src="https://www.googletagmanager.com/gtag/js?id=G-0QBP117RR3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-0QBP117RR3');
</script>
'''
