baseURL = 'https://orginux.github.io'
languageCode = 'en-us'
title = 'Denis Gorobets'  # Made more professional with full name
theme = "hugo-blog-awesome"
enableRobotsTXT = true
pygmentsStyle = "swapoff"
enableEmoji = true
defaultContentLanguage = "en-gb"  # Added for proper date formatting

googleAnalytics = 'G-0QBP117RR3'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'hrdark'
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[params]
  sitename = "Denis Gorobets"
  defaultColor = "auto"
  description = "Data Infrastructure Engineer | Architecting Scalable Real-Time Data Systems with ClickHouse"
  mainSections = ['posts']
  toc = true
  rssFeedDescription = "summary"
  metaKeywords = ["clickhouse", "go", "devops", "linux", "duckdb", "golang", "data"]

[menu]
  [[menu.main]]
    pageRef = "/"
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    pageRef = "posts"
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    pageRef = "tags"
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[params.author]
  avatar = "/images/orx.jpg"
  intro = "Gorobets Denis"
  name = "Gorobets Denis"
  description = "Data Infrastructure Engineer | Architecting Scalable Real-Time Data Systems with ClickHouse"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/orginux"

[[params.socialIcons]]
name = "github"
url = "https://github.com/orginux"

[[params.socialIcons]]
name = "kaggle"
url = "https://www.kaggle.com/denisgorobets"

[[params.socialIcons]]
name = "email"
url = "mailto:orginux@pm.me"

[[params.socialIcons]]
name = "rss"
url = "index.xml"  # Added RSS feed

[privacy]
  [privacy.googleAnalytics]
    disable = false
