baseURL = 'https://orginux.github.io'
languageCode = 'en-us'
title = 'orginux'
theme = 'gokarna-orx'
enableRobotsTXT = true
pygmentsStyle = "dracula"

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"

    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
# index page
avatarURL = "/images/orx.jpg"
avatarSize = "size-xs"
description = "Everything is permitted, Nothing is true"
showPostsOnHomePage = "recent" # "recent" or "popular"

# analitics
metaKeywords = ["clickhouse", "go", "devops"]
customHeadHTML = '''
<script async src="https://www.googletagmanager.com/gtag/js?id=G-0QBP117RR3"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-0QBP117RR3');
</script>
'''

# common
accentColor = "#24B12B"
togglePreviousAndNextButtons = "true"
dateFormat = "2006-01-02"
